version: '3.8'

services:
  mybots:
    build: .
    container_name: mybots-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_DEBUG=False
      - SECRET_KEY=${SECRET_KEY:-change-this-secret-key}
      - BOTS_FILE=/app/data/bots_data.json
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
